// Demo data for DEMO_MODE — based on real Naava Takst sheet rows for verification.
// Used to verify that webapp layout/calculations match the production data structure.
// In real (non-demo) operation, data is read from the live Google Sheet.

const OPPDRAG = [
  {
    kanFaktureres: false,
    oppdragsnr: 'NT-202603-025',
    datoMottatt: '04.03.2026 21:56',
    kilde: 'Megler-epost',
    scanIvit: false,
    oppdragstype: 'Vurderingsoppdrag',
    adresse: 'Åsegardsvegen 46',
    oppdragsgiver: 'Cornelius Rakvåg',
    selger: 'Cornelius Rakvåg',
    selgerTlf: '',
    selgerEpost: '',
    megler: 'Cornelius Rakvag',
    meglerEpost: 'crakva@gmail.com',
    fakturaRef: '',
    status: 'Mottatt',
    fakturaSendesTil: '',
    fakturamotaker: 'huseier',
    boligtype: '',
    areal: '',
    antallTilleggsbygg: '',
    rapporttype: 'Vurderingsrapport',
    medMarkedsverdi: false,
    timer: '',
    prisInkl: null,
    prisEks: null,
    mvaBelop: null,
    avstandKm: 240,
    reiseEks: 1900,
    reiseInkl: 2375,
    sumFergeBom: '',
    antallDeleReise: '',
    befaringDato: '',
    befaringKl: '',
    datoStatusendring: '04.03.2026 21:56',
    timestamp: '2026-03-04T20:56:38.000Z',
    linkMappe: 'https://drive.google.com/drive/folders/1FqZpWCSzhdLUmIEUgb_0D_AMNUEwVK0U',
    notater: 'Åsegardsvegen 46 | Reise: 240 km t/r, 190 km fakturerbart',
    produktnummer: '',
    kommentarRegnskap: '',
    kansellert: false,
  },
  {
    kanFaktureres: false,
    oppdragsnr: 'NT-202603-025',
    datoMottatt: '03.03.2026 16:34',
    kilde: 'IVIT',
    scanIvit: false,
    oppdragstype: 'Tilstandsrapport',
    adresse: 'Øvre Strandgate 21, 6005 ÅLESUND',
    oppdragsgiver: '',
    selger: 'Sigrid Elida Linnerud',
    selgerTlf: '+4746862619',
    selgerEpost: 'elidalinnerud@gmail.com',
    megler: 'Henrik Pettersen',
    meglerEpost: 'no-reply.takst@ivit.no',
    fakturaRef: '1-0022/26',
    status: 'Oppdrag fullført',
    fakturaSendesTil: '',
    fakturamotaker: '',
    boligtype: 'Leilighet',
    areal: 43,
    antallTilleggsbygg: 0,
    rapporttype: '',
    medMarkedsverdi: false,
    timer: '',
    prisInkl: 10000,
    prisEks: 8000,
    mvaBelop: 2000,
    avstandKm: 15,
    reiseEks: 0,
    reiseInkl: 0,
    sumFergeBom: '',
    antallDeleReise: '',
    befaringDato: '12.03.2026',
    befaringKl: '14:00 - 16:00',
    datoStatusendring: '29.04.2026 00:33',
    timestamp: '2026-03-03T15:34:19.000Z',
    linkMappe: 'https://drive.google.com/drive/folders/1-SE6lMF3tjqiJGMFgFMbqQ3PcZ9cKZ-R',
    notater: 'Reise: 15 km t/r (inkludert)',
    produktnummer: '',
    kommentarRegnskap: '',
    kansellert: false,
  },
  {
    kanFaktureres: false,
    oppdragsnr: 'NT-202603-017',
    datoMottatt: '02.03.2026 15:42',
    kilde: 'IVIT',
    scanIvit: false,
    oppdragstype: 'Tilstandsrapport',
    adresse: 'Ringgata 15A, 6005 ÅLESUND',
    oppdragsgiver: '',
    selger: 'Sandra Terøy',
    selgerTlf: '+4799162014',
    selgerEpost: 'sandra-teroey@hotmail.com',
    megler: 'Henrik Pettersen',
    meglerEpost: 'no-reply.takst@ivit.no',
    fakturaRef: '1-0052/26',
    status: 'Oppdrag fullført',
    fakturaSendesTil: '',
    fakturamotaker: 'huseier',
    boligtype: 'Leilighet',
    areal: 78,
    antallTilleggsbygg: 0,
    rapporttype: '',
    medMarkedsverdi: false,
    timer: '',
    prisInkl: 10000,
    prisEks: 8000,
    mvaBelop: 2000,
    avstandKm: 15,
    reiseEks: 0,
    reiseInkl: 0,
    sumFergeBom: '',
    antallDeleReise: '',
    befaringDato: '18.03.2026',
    befaringKl: '10:00 - 12:00',
    datoStatusendring: '29.04.2026 00:32',
    timestamp: '2026-03-02T14:42:33.000Z',
    linkMappe: 'https://drive.google.com/drive/folders/1_kr6Cs34uDVvw_BgbgeaS-OYEz0AUh0U',
    notater: 'Reise: 15 km t/r (inkludert) | [iVit Feil: Login failed — still on login page after submitting credentials]',
    produktnummer: '',
    kommentarRegnskap: '',
    kansellert: false,
  },
  {
    kanFaktureres: false,
    oppdragsnr: 'NT-202602-010',
    datoMottatt: '24.02.2026 09:33',
    kilde: 'IVIT',
    scanIvit: false,
    oppdragstype: 'Tilstandsrapport',
    adresse: 'Voldsundvegen 10, 6094 LEINØY',
    oppdragsgiver: '',
    selger: 'John Normann Pettersen',
    selgerTlf: '+4791327779',
    selgerEpost: 'john.normann.pettersen@gmail.com',
    megler: 'Ludvig Sandström',
    meglerEpost: 'no-reply.takst@ivit.no',
    fakturaRef: '3-0026/26',
    status: 'Befart',
    fakturaSendesTil: '',
    fakturamotaker: 'huseier',
    boligtype: 'Enebolig/fritidsbolig',
    areal: 77,
    antallTilleggsbygg: 0,
    rapporttype: '',
    medMarkedsverdi: false,
    timer: '',
    prisInkl: 16000,
    prisEks: 12800,
    mvaBelop: 3200,
    avstandKm: 110,
    reiseEks: 600,
    reiseInkl: 750,
    sumFergeBom: '',
    antallDeleReise: '',
    befaringDato: '26.02.2026',
    befaringKl: '14:00 - 16:00',
    datoStatusendring: '30.04.2026 00:04',
    timestamp: '2026-02-24T08:33:03.000Z',
    linkMappe: 'https://drive.google.com/drive/folders/12ZE7cn_Sqtza2nz92y8pamgUMWqa8Om9',
    notater: 'Reise: 110 km t/r, 60 km fakturerbart',
    produktnummer: '',
    kommentarRegnskap: '',
    kansellert: false,
  },
  {
    kanFaktureres: false,
    oppdragsnr: 'NT-202602-011',
    datoMottatt: '24.02.2026 09:31',
    kilde: 'IVIT',
    scanIvit: false,
    oppdragstype: 'Tilstandsrapport',
    adresse: 'Gjerdsvegen 7, 6104 VOLDA',
    oppdragsgiver: '',
    selger: 'Hans Arne Foldal',
    selgerTlf: '+4799101657',
    selgerEpost: 'ha.foldal@gmail.com',
    megler: 'Ludvig Sandström',
    meglerEpost: 'no-reply.takst@ivit.no',
    fakturaRef: '3-0015/26',
    status: 'Oppdrag fullført',
    fakturaSendesTil: '',
    fakturamotaker: 'huseier',
    boligtype: 'Enebolig/fritidsbolig',
    areal: 256,
    antallTilleggsbygg: 1,
    rapporttype: 'Tilstandsrapport',
    medMarkedsverdi: true,
    timer: '',
    prisInkl: 23250,
    prisEks: 18600,
    mvaBelop: 4650,
    avstandKm: 170,
    reiseEks: 1200,
    reiseInkl: 1500,
    sumFergeBom: '',
    antallDeleReise: 2,
    befaringDato: '24.02.2026',
    befaringKl: '10:00 - 13:00',
    datoStatusendring: '30.04.2026 00:04',
    timestamp: '2026-02-24T08:31:36.000Z',
    linkMappe: 'https://drive.google.com/drive/folders/1pFMtCT0iSVrPdxr7dYMUQMmYZqg4777k',
    notater: 'Reise: 170 km t/r, 120 km fakturerbart',
    produktnummer: '',
    kommentarRegnskap: '',
    kansellert: false,
  },
  {
    kanFaktureres: false,
    oppdragsnr: 'NT-202602-009',
    datoMottatt: '25.02.2026 22:35',
    kilde: 'IVIT',
    scanIvit: false,
    oppdragstype: 'Tilstandsrapport',
    adresse: 'Smithsgata 5, 6100 VOLDA',
    oppdragsgiver: '',
    selger: 'Mathias Berknes',
    selgerTlf: '+4748281766',
    selgerEpost: 'mathiasberknes@hotmail.com',
    megler: 'Ludvig Sandström',
    meglerEpost: 'no-reply.takst@ivit.no',
    fakturaRef: '3-0028/26',
    status: 'Oppdrag fullført',
    fakturaSendesTil: '',
    fakturamotaker: 'huseier',
    boligtype: 'Enebolig/fritidsbolig',
    areal: 165,
    antallTilleggsbygg: 0,
    rapporttype: '',
    medMarkedsverdi: false,
    timer: '',
    prisInkl: 18000,
    prisEks: 14400,
    mvaBelop: 3600,
    avstandKm: 110,
    reiseEks: 600,
    reiseInkl: 750,
    sumFergeBom: '',
    antallDeleReise: '',
    befaringDato: '12.03.2026',
    befaringKl: '13:00 - 15:00',
    datoStatusendring: '29.04.2026 00:32',
    timestamp: '2026-02-25T21:35:53.000Z',
    linkMappe: 'https://drive.google.com/drive/folders/11oAzmDuCnJxQ7ARAyt4mlP21i0DhGufq',
    notater: 'Reise: 170 km t/r, 120 km fakturerbart',
    produktnummer: '',
    kommentarRegnskap: '',
    kansellert: false,
  },
  {
    kanFaktureres: false,
    oppdragsnr: 'NT-202602-019',
    datoMottatt: '27.02.2026 14:52',
    kilde: 'IVIT',
    scanIvit: false,
    oppdragstype: 'Tilstandsrapport',
    adresse: 'Østre Svinøyvegen 14, 6014 ÅLESUND',
    oppdragsgiver: '',
    selger: 'Linn Kristin Johansen',
    selgerTlf: '+4799468021',
    selgerEpost: 'linnkjo88@gmail.com',
    megler: 'Ole-Marius Heggstad',
    meglerEpost: 'no-reply.takst@ivit.no',
    fakturaRef: '24260001',
    status: 'Befart',
    fakturaSendesTil: '',
    fakturamotaker: '',
    boligtype: 'Enebolig/fritidsbolig',
    areal: 0,
    antallTilleggsbygg: 1,
    rapporttype: '',
    medMarkedsverdi: false,
    timer: '',
    prisInkl: 17250,
    prisEks: 13800,
    mvaBelop: 3450,
    avstandKm: 17,
    reiseEks: 0,
    reiseInkl: 0,
    sumFergeBom: '',
    antallDeleReise: '',
    befaringDato: '13.03.2026',
    befaringKl: '09:00 - 12:00',
    datoStatusendring: '30.04.2026 00:04',
    timestamp: '2026-02-27T13:52:22.000Z',
    linkMappe: 'https://drive.google.com/drive/folders/1sihwGEPfP6t7ocfc5vI06TDQJXShsr2s',
    notater: 'Reise: 17 km t/r (inkludert)',
    produktnummer: '',
    kommentarRegnskap: '',
    kansellert: false,
  },
  {
    kanFaktureres: false,
    oppdragsnr: 'NT-202602-022',
    datoMottatt: '27.02.2026 14:50',
    kilde: 'IVIT',
    scanIvit: false,
    oppdragstype: 'Tilstandsrapport',
    adresse: 'Valderhaugbakkane 11, 6050 VALDERØYA',
    oppdragsgiver: '',
    selger: 'Lars Hallvard Vikås',
    selgerTlf: '+4748036280',
    selgerEpost: 'lars.vikaas@live.no',
    megler: 'Ole-Marius Heggstad',
    meglerEpost: 'no-reply.takst@ivit.no',
    fakturaRef: '24260002',
    status: 'Oppdrag fullført',
    fakturaSendesTil: '',
    fakturamotaker: '',
    boligtype: 'Enebolig/fritidsbolig',
    areal: 184,
    antallTilleggsbygg: 2,
    rapporttype: '',
    medMarkedsverdi: false,
    timer: '',
    prisInkl: 20500,
    prisEks: 16400,
    mvaBelop: 4100,
    avstandKm: 36,
    reiseEks: 0,
    reiseInkl: 0,
    sumFergeBom: '',
    antallDeleReise: '',
    befaringDato: '23.02.2026',
    befaringKl: '12:00 - 14:00',
    datoStatusendring: '30.04.2026 00:05',
    timestamp: '2026-02-27T13:50:44.000Z',
    linkMappe: '',
    notater: 'Reise: 36 km t/r (inkludert)',
    produktnummer: '',
    kommentarRegnskap: '',
    kansellert: false,
  },
  {
    kanFaktureres: false,
    oppdragsnr: 'NT-202603-038',
    datoMottatt: '12.03.2026 13:38',
    kilde: 'IVIT',
    scanIvit: false,
    oppdragstype: 'Tilstandsrapport',
    adresse: 'Koparstadvegen 108, 6098 NERLANDSØY',
    oppdragsgiver: '',
    selger: 'Vidar Kvalsund',
    selgerTlf: '+4748116026',
    selgerEpost: 'vidar@bergshaugen.com',
    megler: 'Ludvig Sandström',
    meglerEpost: 'no-reply.takst@ivit.no',
    fakturaRef: '3-0039/26',
    status: 'Oppdrag fullført',
    fakturaSendesTil: '',
    fakturamotaker: '',
    boligtype: 'Enebolig/fritidsbolig',
    areal: 0,
    antallTilleggsbygg: 1,
    rapporttype: '',
    medMarkedsverdi: false,
    timer: '',
    prisInkl: 17250,
    prisEks: 13800,
    mvaBelop: 3450,
    avstandKm: 170,
    reiseEks: 1200,
    reiseInkl: 1500,
    sumFergeBom: '',
    antallDeleReise: '',
    befaringDato: '26.03.2026',
    befaringKl: '09:00 - 12:00',
    datoStatusendring: '15.05.2026 15:31',
    timestamp: '2026-03-12T12:38:21.000Z',
    linkMappe: 'https://drive.google.com/drive/folders/19Hwh3PGJLFCILdLYAIqEXicPXb00aCwD',
    notater: 'Reise: 170 km t/r, 120 km fakturerbart | [iVit Feil: Login failed — still on login page after submitting credentials]',
    produktnummer: '5',
    kommentarRegnskap: '',
    kansellert: false,
  },
];

function getDemoDashboardData() {
  const now = new Date();
  const curMonth = now.getMonth();
  const curYear = now.getFullYear();

  const statusCounts = {};
  let utestaendeInkl = 0;
  let omsMaaned = 0;
  let omsAar = 0;
  let sumPris = 0;
  let countPris = 0;

  for (const o of OPPDRAG) {
    statusCounts[o.status] = (statusCounts[o.status] || 0) + 1;

    const prisInkl = Number(o.prisInkl) || 0;
    const reiseInkl = Number(o.reiseInkl) || 0;

    if (o.status === 'Kan faktureres') {
      utestaendeInkl += prisInkl + reiseInkl;
    }
    // All oppdrag med pris teller — unntatt kansellerte
    const isCancelled = o.status === 'Oppdrag kansellert';
    if (!isCancelled && prisInkl > 0) {
      omsAar += prisInkl;
      const m = (o.datoStatusendring || o.datoMottatt || '').match(/^(\d{2})\.(\d{2})\.(\d{4})/);
      if (m) {
        const mm = parseInt(m[2], 10) - 1;
        const yyyy = parseInt(m[3], 10);
        if (mm === curMonth && yyyy === curYear) {
          omsMaaned += prisInkl;
        }
      }
      sumPris += prisInkl;
      countPris++;
    }
  }

  const total = OPPDRAG.length;
  const doneCount =
    (statusCounts['Fakturert'] || 0) +
    (statusCounts['Oppdrag kansellert'] || 0) +
    (statusCounts['Oppdrag fullført'] || 0);
  const active = total - doneCount;

  // Project to the shape data.js getDashboardData returns
  const projected = OPPDRAG.map((o, idx) => ({
    rowNum: idx + 2,
    ...o,
  }));

  return {
    success: true,
    demoMode: true,
    testMode: false,
    total,
    active,
    utestaendeInkl,
    omsMaaned,
    omsAar,
    snittPrisInkl: countPris ? Math.round(sumPris / countPris) : 0,
    oppdrag: projected,
    statusCounts,
  };
}

function getDemoOppdrag(rowNum) {
  const idx = rowNum - 2;
  if (idx < 0 || idx >= OPPDRAG.length) return null;
  return { rowNum, ...OPPDRAG[idx] };
}

module.exports = { getDemoDashboardData, getDemoOppdrag, OPPDRAG };
